### ISSUE TITLE
getAllTickers returns null

### ISSUE THREAD

**Issue by Geczy** [chiefsmurph/robinhood-playground#3]
allStocks.json contents:
```json
[
  null
]
```

![image](https://user-images.githubusercontent.com/1036968/37237222-db950b7e-23de-11e8-8994-e0a1ba6e79a0.png)

**Comment by Geczy** [comment]
Issue was because config.js was in the wrong format, has to be like this:

```
const credentials = {
  "username": "x",
  "password": "x"
}

module.exports = { credentials }
```

**Comment by chiefsmurph** [comment]
I like your dedication to getting this running.
