### ISSUE TITLE
can't clone due to invalid filenames

### ISSUE THREAD

**Issue by Geczy** [chiefsmurph/robinhood-playground#4]
such as `<$3` windows does not allow these filenames , recommend renaming to exclude special characters

**Comment by chiefsmurph** [comment]
interesting thank you for the heads up

**Comment by chiefsmurph** [comment]
it should finally be fixed with the final removal of $'s in 

https://github.com/chiefsmurph/robinhood-playground/commit/355888ea5e8409581ee5900d5a714e3737c23d9e#diff-b96113a0ba98e70bba4158a97219d071

**Comment by chiefsmurph** [comment]
let me know if you still have trouble cloning

**Comment by Geczy** [comment]
New clone worked great, thanks !
