### ISSUE TITLE
pattern-predict is unavailable submodule

### ISSUE THREAD

**Issue by Geczy** [chiefsmurph/robinhood-playground#5]
```
No submodule mapping found in .gitmodules for path 'modules/pattern-predict'
```

Have to add `.gitmodules` file with 

```
[submodule "modules/pattern-predict"]
	path = modules/pattern-predict
	url = git://github.com/chiefsmurph/pattern-predict.git
```

Then run `git pull && git submodule init && git submodule update && git submodule status`

**Comment by chiefsmurph** [comment]
Are you getting this error?  Or are you suggesting to use submodule to hook up with the other repo?

**Comment by chiefsmurph** [comment]
This worked thanks! https://github.com/chiefsmurph/robinhood-playground/commit/f6873ab8e4521afb13506b665c1b448ad978b377
