### ISSUE TITLE
Posible inverse condition in strategy

### ISSUE THREAD

**Issue by joadgaji** [chiefsmurph/robinhood-playground#8]
https://github.com/chiefsmurph/robinhood-playground/blob/4859bb8b09d8e63da42b44cab044f276b94dfe66/modules/constant-downers.js#L34

I think the condition is less than instead.

**Comment by chiefsmurph** [comment]
Wow! Thank you, @joadgaji .  You are absolutely correct.  Can't believe I have had it like this for this long.

**Comment by chiefsmurph** [comment]
https://github.com/chiefsmurph/robinhood-playground/commit/e999af34542d1d3042f1100f104ef4f21963c8e7
